# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-20 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='name',
            field=models.CharField(default='Sample Image', max_length=128),
        ),
    ]
